### ISSUE TITLE
Pose adaptation while stepping

### ISSUE THREAD

**Issue by IoannisDadiotis** [ADVRHumanoids/casannis-walking#4]
Hi @alaurenzi . I created this issue for discussing future thoughts about the desired pose adaptation that we will possibly need for the stepping centauro.

At first, looking at my current [stack](https://github.com/ADVRHumanoids/casannis-walking/blob/master/config/centauro_stack.yaml) used for stepping, I would like to ask about the `Postural` task. The task definition follows:
```
Postural:
    type: "Postural"
    lambda: 0.01
    weight:
        VIRTUALJOINT_1: 0.0
        VIRTUALJOINT_2: 0.0
        VIRTUALJOINT_3: 0.0
        VIRTUALJOINT_4: 0.0
        VIRTUALJOINT_5: 0.0
        VIRTUALJOINT_6: 0.0
```
I didn't find much info on this on the [Cartesio Doc](https://advrhumanoids.github.io/CartesianInterface/tasks/postural.html). Can you help me understand what does a postural task exactly regulate, does it have to do with the robot pose ?
What is the quantity of the robot kinematics that the names `VIRTUALJOINT_*` represent?

Thanks
